# Generated by Django 4.2.7 on 2025-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
